language: python
python: 2.7
install:
  - pip install tox
env:
  - TOXENV=py27-django1.8
  - TOXENV=py27-django1.9
  - TOXENV=py34-django1.8
  - TOXENV=py34-django1.9
  - TOXENV=py35-django1.8
  - TOXENV=py35-django1.9
  - TOXENV=pypy-django1.8
  - TOXENV=pypy-django1.9
  - TOXENV=py27-django1.10
  - TOXENV=py35-django1.10
  - TOXENV=py34-django1.10
  - TOXENV=pypy-django1.10
script:
  - tox -e $TOXENV
